image: node:8.9.4

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          # Add SSH keys for private dependencies
          - mkdir -p ~/.ssh
          - echo $SSH_KEY | base64 -d > ~/.ssh/id_rsa
          - chmod 600 ~/.ssh/id_rsa

          # Install and run checks
          - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
          - export PATH=$HOME/.yarn/bin:$PATH
          - yarn install # Build is triggered from the postinstall hook

  branches:
    master:
      - step:
          caches:
            - node
          script:
            # Add SSH keys for deployment
            - mkdir -p ~/.ssh
            - echo $SSH_KEY | base64 -d > ~/.ssh/id_rsa
            - chmod 600 ~/.ssh/id_rsa

            # Deploy to hosting
            - git remote add dokku $DOKKU_REMOTE_URL
            - git push dokku master
